name: Build Xbox Appx
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-2022
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download Runtime Libraries and Assets
        run: |
          Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass
          .\download_libs.ps1
          .\download_assets.ps1

      - name: Build with manual SDK path
        shell: cmd
        run: |
          set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\ucrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared
          set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\um\x64;C:\Program Files (x86)\Windows Kits\10\Lib\10.0.22621.0\ucrt\x64
          powershell -ExecutionPolicy Bypass -File .\build.ps1

      - name: Upload Finished Appx Bundle
        uses: actions/upload-artifact@v4
        with:
          name: Xbox-Installer
          path: |
            **/*.appx
            **/*.msix
            
